### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by p1r473** [xorcan/hosts#1]
invalid domains:

      - 1.black-snake-oil.info​
      - black-snake-oil.info​
      - www.1.black-snake-oil.info​
      - www.black-snake-oil.info​
      - www.yapıkredi.com
      - yapıkredi.com

**Comment by oktayaa** [comment]
What about them is invalid?

**Comment by p1r473** [comment]
They are being picked up as invalid in the PiHole gravity script..
I think they are using alternative characters in them.  May be using non-ascii characters?

Perhaps maybe we delete them and re-add them by typing them manually?

**Comment by oktayaa** [comment]
There's a standard for international domain names for domain names that contain non-English Ascii characters. They are not very popular but they are allowed as far as I know.

I don't maintain this list though. Maybe the owner can remove them. What's wrong with the other domains?

**Comment by p1r473** [comment]
All of them are being picked up as invalid by the PiHole gravity script
Its possible that some of the characters that LOOK like ASCII characters are not actually ASCII characters
I recommend removing them and re-typing them by hand, instead of copying and pasting them.

As PiHole is viewing these domains as invalid, it will not block them (it just ignores them)

```
  [i] Target: https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt
  [✓] Status: Retrieval successful
  [i] Received 8394 domains, 6 domains invalid!
      Sample of invalid domains:
      - 1.black-snake-oil.info​
      - black-snake-oil.info​
      - www.1.black-snake-oil.info​
      - www.black-snake-oil.info​
      - www.yapıkredi.com
```

**Comment by p1r473** [comment]
I can see the 'ı' character in the 'yapıkredi' domains
I have no idea whats wrong with the black-snake-oil domains.

You can ignore them I guess, I was just reporting it in case theres anything that you want to fix.

**Comment by oktayaa** [comment]
I am sure xorcan will know what to do. I am a user like yourself.

**Comment by xorcan** [comment]
> 
> 
> All of them are being picked up as invalid by the PiHole gravity script
> Its possible that some of the characters that LOOK like ASCII characters are not actually ASCII characters
> I recommend removing them and re-typing them by hand, instead of copying and pasting them.
> 
> As PiHole is viewing these domains as invalid, it will not block them (it just ignores them)
> 
> ```
>   [i] Target: https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt
>   [✓] Status: Retrieval successful
>   [i] Received 8394 domains, 6 domains invalid!
>       Sample of invalid domains:
>       - 1.black-snake-oil.info​
>       - black-snake-oil.info​
>       - www.1.black-snake-oil.info​
>       - www.black-snake-oil.info​
>       - www.yapıkredi.com
>       - yapıkredi.com
> ```

in nano adblocker (ublock origin fork), blocking works good.
yapıkredi includes a non-english character "ı" or "I" this is causing issue.
other urls are good. i dont know why causing trouble.
these are pishing urls. i giving the real urls. can you try these:

xn--yapkredi-vkb.com
xn--yapkredi-vkb.com
xn--yapikredi-ekf.com
xn--yapikredi-8jf.com
xn--yapikiredi-w2f.com
xn--yapikredi-8jff.com

**Comment by p1r473** [comment]
Output:
```
[i] Target: https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt
  [✓] Status: Retrieval successful
  [i] Received 8590 domains, 90 domains invalid!
      Sample of invalid domains:
      - www.www.yapikredı.com
      - www.www.yapikredı.com.tr
      - www.www.yapikredı.edu
      - www.www.yapikredı.edu.tr
      - www.www.yapikredı.gov
      - www.www.yapikredı.gov.info.tr
      - www.www.yapikredı.gov.tr
      - www.www.yapikredı.info
      - www.www.yapikredı.net
      - www.www.yapikredı.tr
      - www.www.yapıkredi.com
      - www.www.yapıkredi.com.tr
      - www.www.yapıkredi.edu
      - www.www.yapıkredi.edu.tr
      - www.www.yapıkredi.gov
      - www.www.yapıkredi.gov.info.tr
      - www.www.yapıkredi.gov.tr
      - www.www.yapıkredi.info
      - www.www.yapıkredi.net
      - www.www.yapıkredi.tr
      - www.www.yapıkredı.com
      - www.www.yapıkredı.com.tr
      - www.www.yapıkredı.edu
      - www.www.yapıkredı.edu.tr
      - www.www.yapıkredı.gov
      - www.www.yapıkredı.gov.info.tr
      - www.www.yapıkredı.gov.tr
      - www.www.yapıkredı.info
      - www.www.yapıkredı.net
      - www.www.yapıkredı.tr
      - www.yapikredı.com
      - www.yapikredı.com.tr
      - www.yapikredı.edu
      - www.yapikredı.edu.tr
      - www.yapikredı.gov
      - www.yapikredı.gov.info.tr
      - www.yapikredı.gov.tr
      - www.yapikredı.info
      - www.yapikredı.net
      - www.yapikredı.tr
      - www.yapıkredi.com
      - www.yapıkredi.com.tr
      - www.yapıkredi.edu
      - www.yapıkredi.edu.tr
      - www.yapıkredi.gov
      - www.yapıkredi.gov.info.tr
      - www.yapıkredi.gov.tr
      - www.yapıkredi.info
      - www.yapıkredi.net
      - www.yapıkredi.tr
      - www.yapıkredı.com
      - www.yapıkredı.com.tr
      - www.yapıkredı.edu
      - www.yapıkredı.edu.tr
      - www.yapıkredı.gov
      - www.yapıkredı.gov.info.tr
      - www.yapıkredı.gov.tr
      - www.yapıkredı.info
      - www.yapıkredı.net
      - www.yapıkredı.tr
      - yapikredı.com
      - yapikredı.com.tr
      - yapikredı.edu
      - yapikredı.edu.tr
      - yapikredı.gov
      - yapikredı.gov.info.tr
      - yapikredı.gov.tr
      - yapikredı.info
      - yapikredı.net
      - yapikredı.tr
      - yapıkredi.com
      - yapıkredi.com.tr
      - yapıkredi.edu
      - yapıkredi.edu.tr
      - yapıkredi.gov
      - yapıkredi.gov.info.tr
      - yapıkredi.gov.tr
      - yapıkredi.info
      - yapıkredi.net
      - yapıkredi.tr
      - yapıkredı.com
      - yapıkredı.com.tr
      - yapıkredı.edu
      - yapıkredı.edu.tr
      - yapıkredı.gov
      - yapıkredı.gov.info.tr
      - yapıkredı.gov.tr
      - yapıkredı.info
      - yapıkredı.net
      - yapıkredı.tr
```

**Comment by xorcan** [comment]
fixed.
