### ISSUE TITLE
Invalid domain in the blocklist

### ISSUE THREAD

**Issue by p1r473** [xorcan/hosts#11]
The below domains have invalid characters in them. Some of the letters are replaced by alt characters and are not proper domain names due to the illegal characters

www.yapıkredi.com
1.black-snake-oil.info​
black-snake-oil.info​
www.1.black-snake-oil.info​
www.black-snake-oil.info​

**Comment by xorcan** [comment]
eklendi

**Comment by p1r473** [comment]
@xorcan  the following domains are still present with illegal and invalid characters
```
1.black-snake-oil.info​
black-snake-oil.info​
www.1.black-snake-oil.info​
www.black-snake-oil.info​
www.yapıkredi.com
yapıkredi.com
```
