### ISSUE TITLE
Ekleme

### ISSUE THREAD

**Issue by retta1** [xorcan/hosts#12]
||hdfilmizle.pw/uploads/*
||e-kredim.org/wp-content/uploads/rek/*
dizimag.cc#@#body:style(background-image: none!important;)
@@||dizimag.cc/rek/insta.png
turkanime.net##div.col-xs-6:nth-of-type(2)

bunları ekler misin ? :D 
ilk 2si https://hdfilmcehennemi.io/ sitesinde çalışıyor

**Comment by xorcan** [comment]
eklendi
