### ISSUE TITLE
False positive: code.highcharts.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [xorcan/hosts#14]
This is a domain which generates a graph for your needs with data from the main website.

See also: Ultimate-Hosts-Blacklist/xorcan_tuerk_ad_list#1

**Comment by xorcan** [comment]
fixed now. may you try and close issue?

**Comment by Somebodyisnobody** [comment]
It's not applied by teh CI-process in https://github.com/Ultimate-Hosts-Blacklist/xorcan_tuerk_ad_list, i'll close this issue and if there are further problems on your side i'll reopen it.
