### ISSUE TITLE
illegal characters

### ISSUE THREAD

**Issue by p1r473** [xorcan/hosts#22]
@xorcan the following domains are still present with illegal and invalid characters

1.black-snake-oil.info​
black-snake-oil.info​
www.1.black-snake-oil.info​
www.black-snake-oil.info​
www.yapıkredi.com

Türkçe konuşmuyorum ama aşağıdakiler yasa dışı ve geçersiz karakterler içeriyor ve kaldırılması gerekiyor

**Comment by xorcan** [comment]
added real "yapıkredi.com" (xn--yapkredi-vkb.com)
that was not an issue. this sites are illegal and i tried to ban with this lists.
