### ISSUE TITLE
filmmodu.org

### ISSUE THREAD

**Issue by xorcan** [xorcan/hosts#3]
||filmmodu.org/uploads/*ultrabet*.mp4 

satırını ekleyince film açılmıyor.

**Comment by retta1** [comment]
hocam bunu deneyin ||s1.filmmodu.org/uploads/*$media açılıyor o zaman

**Comment by retta1** [comment]
ek olarak bunu yazmaları ayrı bir ironi :D 

Ayrıcalıklarımız

Film sitelerinde film izlemenin en zor ve çekilmez yönlerinden biri de film başlarken zorunlu olarak tıklanması gereken reklamlar veya filmin en heyecanlı yerinde araya giren ücretli reklamlar… Arkadaş, eş-dost ile birlikte veya tek başınıza film izlerken bu tip sorunların yaşanması ciddi anlamda can sıkıcı olabiliyor. Filmmodu ekibi olarak tüm bu olumsuzlukları önleyecek bir adım attık ve reklamsız film izleme imkanını ziyaretçilerimize sunarak istedikleri filmleri daha rahat bir ortamda ve sinirlerin bozulmasına gerek bırakmadan HD film izle kalitesi ile sunduk.

**Comment by xorcan** [comment]
teşekkürler ekledim hocam. umarım çalışır
