### ISSUE TITLE
AdBlock ve AdBlock Plus'a eklenmiyor, "Not a valid filters list" hatası veriyor.

### ISSUE THREAD

**Issue by burak-tarhanli** [xorcan/hosts#6]
Bu listeyi filterlists.com'dan buldum.
Hem AdBlock hem de AdBlock Plus'a https://raw.githubusercontent.com/xorcan/hosts/master/xelement.txt linkini eklemeye çalıştığımda "Failed, not a valid filters list" diyor. Bu listeler sadece Nano ile mi çalışıyorlar?

**Comment by xorcan** [comment]
şimdi dener misin? bildirdiğin için teşekkürler ;)

**Comment by burak-tarhanli** [comment]
Ben teşekkür ederim :) Ama hala çalışmıyor malesef :(  Şimdi aynı linki Chrome'da AdBlock 4.7.3 ile denedim, yine "Failed, not a valid filters list" dedi.

**Comment by burak-tarhanli** [comment]
Karakter encoding sorunu olabileceğini düşündüm ve title'dan kalpleri kaldırdıp denedim, çalıştı.
