### ISSUE TITLE
Film/Dizi izleme sitelerindeki reklamlar (filtreden kaçanlar)

### ISSUE THREAD

**Issue by oktayaa** [xorcan/hosts#7]
Tepedeki bahis bannerını gösteriyor.

! 3/16/2020 https://www.diziizlefull1.com
||www.adbetnetwork.com$subdocument

**Comment by xorcan** [comment]
bildirdiğin için teşekkürler

**Comment by oktayaa** [comment]
! 3/16/2020 https://www.vizyonfilmizle.tv
||vizyonfilmizle.tv/bet.jpg$image

Buraya ekleyeyim. Bir sürü issue olmasın.

**Comment by xorcan** [comment]
istediğin gibi ekle hocam sınır yok :)
