### ISSUE TITLE
[Adblock Plus 2.0]

### ISSUE THREAD

**Issue by p1r473** [xorcan/hosts#9]
Hello,
I have been using your list in my PiHole which uses hosts-file formatted lists
The list is now now longer supported (its detected as ABP)
Can you please comment out the line: [Adblock Plus 2.0]

![image](https://user-images.githubusercontent.com/9235633/76880330-e3b0b280-684d-11ea-9564-90236584d960.png)

![image](https://user-images.githubusercontent.com/9235633/76879980-67b66a80-684d-11ea-88e2-5bb36c73b177.png)

**Comment by xorcan** [comment]
I couldn't understand what you want. I have now removed the xyz line. Was it the added version you want?

**Comment by p1r473** [comment]
Yes, you fixed it, perfect, thanks.
